### ISSUE TITLE
Cannot compile tree-sitter with Clang and MinGW on Windows

### ISSUE THREAD

**Issue by aminya** [tree-sitter/tree-sitter#1889]
## Issues

There are multiple issues related to the incompatibility of Tree-sitter with Clang and MinGW on Windows:

- [x] When running `tree-sitter test`, the code assumes that MSVC is used on Windows and flags, which is not a correct assumption.  Flags not supported by other compilers like Clang and Mingw are used for compilation (e.g. `-fPIC`). Fixed by pull request #1835 

- [x]  `fdopen`, which is a non-standard POSIX function, is used on Windows. This causes compilation errors when `-Werror` is enabled with Clang on Windows because this warning is enabled by default. Fixed by pull request #1411

```cpp
warning: In file included from src\lib.c:12:
warning: src/./parser.c:1781:28: warning: 'fdopen' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fdopen. See online help for details. [-Wdeprecated-declarations]
warning:     self->dot_graph_file = fdopen(fd, "a");
warning:                            ^
warning: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\stdio.h:2431:28: note: 'fdopen' has been explicitly marked deprecated here
warning:         _Check_return_     _CRT_NONSTDC_DEPRECATE(_fdopen)    _ACRTIMP FILE* __cdecl fdopen(_In_ int _FileHandle, _In_z_ char const* _Format);
warning:                            ^
warning: C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt.h:414:50: note: expanded from macro '_CRT_NONSTDC_DEPRECATE'
warning:         #define _CRT_NONSTDC_DEPRECATE(_NewName) _CRT_DEPRECATE_TEXT(             \
warning:                                                  ^
warning: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30133\include\vcruntime.h:310:47: note: expanded from macro '_CRT_DEPRECATE_TEXT'
warning: #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
```

- [x]  'ts_stack__add_slice' is used in an inline function with external linkage. This is technically an error because the inline functions should not be linked statically. This causes compilation errors when `-Werror` is enabled with Clang on Windows because this warning is enabled by default. Fixed by pull request #1411

```cpp
warning: In file included from src\lib.c:14:
warning: src/./stack.c:311:9: warning: static function 'ts_stack__add_slice' is used in an inline function with external linkage [-Wstatic-in-inline]
warning: ts_stack__add_slice(
warning: ^
warning: src/./stack.c:274:1: note: use 'static' to give inline function 'stack__iter' internal linkage
warning: inline StackSliceArray stack__iter(Stack *self, StackVersion version,
warning: ^
warning: static
warning: src/./stack.c:15:16: note: expanded from macro 'inline'
warning: #define inline __forceinline
warning: ^
warning: src/./stack.c:258:13: note: 'ts_stack__add_slice' declared here
warning: static void ts_stack__add_slice(Stack *self, StackVersion original_version,
warning: ^
warning: 1 warning generated.
```
