### ISSUE TITLE
Tree-Sitter Roadmap

### ISSUE THREAD

**Issue by amaanq** [tree-sitter/tree-sitter#2895]
With the release of 0.20.9, I think it'd be nice to be clear and transparent about what we'd like to accomplish for each successive release, as well as to have a proper outline and plan for the next few releases. Ideally we should have one big release and several minor releases per year.

While it'd be nice to get every targeted issue and feature implemented *before* a release, it's not always possible - but that shouldn't delay a release unless it's really crucial.

For those reading this that wish to help out or move any issue they'd like fixed or feature they'd like implemented, don't hesitate! Draft a PR, ask questions, or reach out in the [discord](https://discord.gg/w7nTvsVJhm) to chat more! Any help is appreciated as long as it's high quality and well-thought-out.

# 0.20.10 (ca. April 2024)

### Issues to tackle

- [ ] https://github.com/tree-sitter/tree-sitter/issues/645
- [x] https://github.com/tree-sitter/tree-sitter/issues/703
- [x] https://github.com/tree-sitter/tree-sitter/issues/835
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2021
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2237
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2847
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2611 (Parser introspection?)
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2728
- [ ] https://github.com/tree-sitter/tree-sitter/issues/647 and/or https://github.com/tree-sitter/tree-sitter/issues/2635

### Features/Fixes to Land

- [ ] https://github.com/tree-sitter/tree-sitter/pull/2438 (Needs more testing, triaging, and fixes for multi-grammar repos)
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2478
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2488 (Needs reworking)
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2545
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2647 (Also needs tweaking)
- [ ] Make the last-wins query precedence default, remove first-wins and the optional flag to reverse the behavior
- [ ] Improve CLI output with the parse/query subcommands, ideally with a prettier and/or a more verbose version of the syntax trees

# 0.21.0 (ca. November 2024, big release of the year)

### Issues to tackle

- [ ] https://github.com/tree-sitter/tree-sitter/issues/768
- [ ] https://github.com/tree-sitter/tree-sitter/issues/880
- [ ] https://github.com/tree-sitter/tree-sitter/issues/1644
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2197
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2346 (Might not be doable since it's extremely hard to reproduce)
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2375
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2580
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2620
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2641
- [ ] https://github.com/tree-sitter/tree-sitter/issues/2837
- [ ] Allow grammars to use the allocators in the core library - thus preventing downstream consumers that wish to use their own allocators even in a grammar's scanner.

### Features/Fixes to Land

- [ ] https://github.com/tree-sitter/tree-sitter/pull/1635
- [x] https://github.com/tree-sitter/tree-sitter/pull/2914
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2399
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2400 (needs a rework/redesign)
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2503 (Look into this caching a bit more for better optimizations?)
- [ ] https://github.com/tree-sitter/tree-sitter/pull/2577 (Needs some tweaks)

**Comment by MurageKibicho** [comment]
Reaching out to ask if adding interactive tutorials to the treesitter website could be added to the November 2024 checklist. 

I experiment a lot with Treesitter Playground. Perhaps more tutorials on using the C api - and other apis - could be beneficial to the community. 

I'd be happy to make a PR. Maybe even help maintain the website. Let me know what you think!

**Comment by jasonwilliams** [comment]
Hey @amaanq thanks for the release and update, it looks like web-tree-sitter is still 0.20.8 [on npm](https://www.npmjs.com/package/web-tree-sitter) is there a plan to do a release on there too?

**Comment by Keats** [comment]
Is https://github.com/tree-sitter/tree-sitter/pull/2594 not planned anymore? It was mentioned in another roadmap i believe?

**Comment by dundargoc** [comment]
I've created [milestones](https://github.com/tree-sitter/tree-sitter/milestones) for these issues and PRs. That way we can have a centralized place to set the roadmap rather than scattered around in various issues.

**Comment by dundargoc** [comment]
@amaanq if you want we could close this to avoid duplication. Up to you though, I don't really mind either way.

**Comment by amaanq** [comment]
Yeah the milestones are much better, and we shouldn't need to mention 2 sources of info regarding plans/milestones. I'll close this out but answer some of the feedback/questions

@MurageKibicho, I think that'd be a great idea! It's something I've wanted for a while, but, being a 2 man (now 4 man) team, hard to get in since there's so much other stuff to work on. I was thinking of like a cookbook/mini exercise (akin to rustlings maybe) page for users to learn the ins and outs of tree-sitter. If this is something you would like to work on, please reach out to me in the tree-sitter discord, matrix, or email, whichever you prefer. I can help guide you through this as well :grin: I totally agree newbies struggle **a lot** with tree-sitter when starting out, and it'd be nice to dump experienced people's knowledge/hints/tips/thoughts into the site that's digestible for anyone.

@jasonwilliams, We have a blocker because we currently rely on wasmtime as a dependency for the wasm features. They do not publish their c-api publicly, which crates.io needs when publishing crates (and npm just fetches a rust built release FYI ;) ). However, Max PRed a fix to allow publishing this crate, and it was backported to their v18 release so we can expect a release on crates/npm in a couple weeks.

@Keats, there's a lot to consider with #2594, and, as cool of an idea as it is, there's other, more interesting ways to go about it that have been discussed, such as embedding compiled queries into the .data section at parser compile time (thus resulting in instantly-loadable queries!), or even compiling queries into their own shared object to be dynamically loadable, etc. I think I'd like Max to give his thoughts on that tbh, I wish he had before since he has far more experience and I'd trust his judgement calls way more than my own. I'll poke him to do so :) but tbh, I think we can put that on the roadmap/milestone for the end-of-the-year release.
