### ISSUE TITLE
tree-sitter highlight has does not find the language.

### ISSUE THREAD

**Issue by monoclex** [tree-sitter/tree-sitter#732]
I wanted to try out `tree-sitter highlight` but it seems like it has a near impossible time figuring out what language to use. For example, attempting to run `tree-sitter highlight .\examples\jquery.js` for [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript) yields `No language found for path ".\\examples\\jquery.js"`.

Repro on Linux:
```shell
git clone --depth=1 https://github.com/tree-sitter/tree-sitter-javascript
cd tree-sitter-javascript
npm i
./node_modules/tree-sitter-cli/tree-sitter highlight ./examples/jquery.js

# yields
# No language found for path "./examples/jquery.js"
```

Despite that, `tree-sitter test` is able to run the highlighter tests just fine.

I've tried to get syntax highlighting working in my project, but have had no luck getting either the highlighting tests or the highlight command to work. Hopefully this issue can help shed some light on this problem.

**Comment by patrickt** [comment]
Does it work if you use a global `tree-sitter` executable (from the releases page, or built with `cargo`), rather than the one contained in `node_modules`?

**Comment by grantmacken** [comment]
same problem here, tried latest release and node cli
Can do everything else, generate, test.,parse, use queries, build wasm and use web-ui,
 but  `tree-sitter highlight` fails with the  `No language found for path`

**Comment by SirJosh3917** [comment]
I grabbed a release of tree-sitter from the releases page, sat it in `~/tree-sitter-javascript` and ran `./tree-sitter highlight ./examples/jquery.js` but I still get the same error. I tried to install it globally with `cargo install tree-sitter-cli`, but I ran into #641

**Comment by maxbrunsfeld** [comment]
Have you looked at the docs and set up the configuration like it describes?

https://tree-sitter.github.io/tree-sitter/syntax-highlighting#global-configuration

**Comment by SirJosh3917** [comment]
After adding the correct path (in my case, because the directory I was working in was `~/tree-sitter-javascript`, I had to add `~` to my `parser-directories` path), it does!

It seems odd that tree-sitter doesn't use the same behavior it does for `tree-sitter test` when looking for a highlighter to use. Perhaps it should?

**Comment by Himujjal** [comment]
here's my code:

I only have `highlights.scm` in my queries folder at the moment.

I have the folder in `/home/himu/my_code/zig/projects/tree-sitter-zig`. In `~/.tree-sitter/config.json` I put `/home/himu/my_code/zig/projects` as one of the directories.

I then run `tree-sitter highlight ./corpus/test.zig`. Got the same error.

**Comment by Himujjal** [comment]
> here's my setup:
> 
> I only have `highlights.scm` in my queries folder at the moment.
> 
> I have the folder in `/home/himu/my_code/zig/projects/tree-sitter-zig`. In `~/.tree-sitter/config.json` I put `/home/himu/my_code/zig/projects` as one of the directories.
> 
> I then run `tree-sitter highlight ./corpus/test.zig`. Got the same error.

**Comment by dfgordon** [comment]
I have been getting the same error with my own projects and also `github.com/tree-sitter/tree-sitter-go`.  I tried the advice on this thread without success.

Strangely for me, however, it goes back and forth (seemingly at random) between `No language found...` and `thread 'main' panicked...`. I can't figure out the condition that triggers one or the other alternative.  Under no condition do I get success.

Here is a short terminal session illustrating some details of the thread panic:

```
[gordon@hypersonic ~]$ cd codes/tree-sitter-go/
[gordon@hypersonic tree-sitter-go]$ tree-sitter --version
tree-sitter 0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8)
[gordon@hypersonic tree-sitter-go]$ tree-sitter test > test.out
[gordon@hypersonic tree-sitter-go]$ tail test.out -n 3
    ✓ Channel types
    ✓ Function types
    ✓ Type Aliases
[gordon@hypersonic tree-sitter-go]$ tree-sitter highlight examples/value.go 
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 10', cli/src/highlight.rs:359:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[gordon@hypersonic tree-sitter-go]$ export RUST_BACKTRACE=1
[gordon@hypersonic tree-sitter-go]$ tree-sitter highlight examples/value.go 
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 6', cli/src/highlight.rs:359:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:69:5
   3: tree_sitter_cli::highlight::ansi
   4: tree_sitter::run
   5: tree_sitter::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[gordon@hypersonic tree-sitter-go]$ head ~/.config/tree-sitter/config.json -n 5
{
  "parser-directories": [
    "/home/gordon/codes"
  ],
  "theme": {
[gordon@hypersonic tree-sitter-go]$ pwd
/home/gordon/codes/tree-sitter-go
[gordon@hypersonic tree-sitter-go]$ ls ~/.cache/tree-sitter/lib
go.so
[gordon@hypersonic tree-sitter-go]$ cat /etc/centos-release
CentOS Linux release 8.4.2105
```

**Comment by dfgordon** [comment]
A couple more notes:

I had a directory `~/.tree-sitter` with other configuration files which I suppose is an older directory structure now replaced by `~/.config/tree-sitter`.  Cleaning out the old had no apparent effect.

The documentation mentions creating library files using `make`, I wasn't clear on whether having such a library in `~/.cache` or anywhere else would make any difference to `highlight`, or how to create/obtain the `Makefile`.  I noted shared libraries showing up in `~/.cache` at times, but have not understood the conditions that produce them.

**Comment by alemuller** [comment]
Things that worked for me in the past.

First. See the path of the config file with `tree-sitter init-config`
```
$ tree-sitter init-config
Remove your existing config file first: /home/muller/.tree-sitter/config.json
```

Now, see if the `"parser-directories" in the `config.json`` is set correctly:

If your grammar is at `/home/foo/git/tree-sitter-go/src/parser.c` the `parser-directories` should include `/home/foo/git`.

Run `tree-sitter generate` at `tree-sitter-go`. I had issues fix themselves after running this (might have been a coincidence).

See if there is any path on `tree-sitter-go/package.json` and make sure they are correctly set.

**Comment by dfgordon** [comment]
Thanks @alemuller I didn't think to try `tree-sitter dump-languages`.  It does find the language but I noticed all languages have `highlights: None`, per following terminal dump:

```
(base) [gordon@hypersonic tree-sitter-go]$ tree-sitter dump-languages
scope: input.turbowave
parser: "/home/gordon/codes/tree-sitter-turbowave/"
highlights: None
file_types: ["tw"]
content_regex: None
injection_regex: None

scope: source.bas
parser: "/home/gordon/codes/tree-sitter-applesoft/"
highlights: None
file_types: ["bas"]
content_regex: None
injection_regex: None

scope: source.go
parser: "/home/gordon/codes/tree-sitter-go/"
highlights: None
file_types: ["go"]
content_regex: None
injection_regex: None
```

Is that a clue?  The rest seems to check out.  I did try `tree-sitter generate` as well (again) but still the same thread panic.

**Comment by dfgordon** [comment]
This started working for me only after I rolled back both node and tree-sitter versions.  I was doing this to make Atom happy, but it also fixed `tree-sitter highlight`.  I am now using node 12.14.1 and TS 0.17.3. So `thread 'main' panicked...` may be coming from some bug in later versions, whereas `No language found...` is more to do with the configuration settings, as discussed above.

**Comment by alemuller** [comment]
Only saw this post today.

If you are rolling back versions, you probably want to recompile your languages.

I also getting `highlights: None`. But running `tree-sitter highlight` seems to work.

**Comment by verdverm** [comment]
I'm seeing the module I'm trying to author, but it's output in `dump-languages` looks wrong. Ringing my head after following the docs and suggestions here. I've tried both the local and globally installed tree-sitter, both giving the same results.

```
$ tree-sitter --version
tree-sitter 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5)

$ tree-sitter dump-languages
scope: 
parser: "/home/tony/nvim/tree-sitter-cue"
highlights: None
file_types: []
content_regex: None
injection_regex: None

$ tree-sitter highlight test/cue/first.cue
No language found for path "test/cue/first.cue"

$ tree-sitter parse test/cue/first.cue
(source_file [0, 0] - [1, 0]
  (decl [0, 0] - [0, 9]
    (label [0, 0] - [0, 5]
      (identifier [0, 0] - [0, 5]))
    (value [0, 7] - [0, 9]
      (number [0, 7] - [0, 9]))))
```

```
  // from package.json
  "tree-sitter": {
    "scope": "source.cue",
    "file-types": ["cue"]
  }
```

```
  // from ~/.config/tree-sitter/config.json
  "parser-directories": [
    "/home/tony/nvim"
  ],
```

Any thoughts or suggestions that could help here?

**Comment by kylegoetz** [comment]
I'm on a Mac. I have the same problem. When I run `./node_modules/tree-sitter-cli/tree-sitter highlight ./test/identifiers.u` (source code I wrote to test highlighting on), I get **No language found for path "./test/identifier.u"**

`package.json`:

```json
"tree-sitter": {
    "scope": "grammar.js",
    "file-types": [
      "u"
    ]
  }
```

I already have run init-config and have `/Users/kylegoetz/Library/Application\ Support/tree-sitter/config.json` with the following relevant content:

```json
{
  "parser-directories": [
    "/Users/kylegoetz/Documents/workspace"
  ],
  "theme": {
    "removed": "from this post to shorten it ",
  }
}

```

My code is located at `/Users/kylegoetz/Documents/workspace/tree-sitter-unison`.

**Comment by ahlinc** [comment]
TODO:
- [ ] Add a tips flag to `tree-sitter generator` that would show suggestions and in this case it will suggest to set the `scope` field as `source.LANG_NAME` by meaning that it's best practice to to name languages with the `source.` prefix.
- [ ] In case of missing language add to `tree-sitter parser` error output suggestions what to check to resolve the issue.
- [ ] Improve `tree-sitter-loader select_language(...)` behaviour. _Actually done, but needs public PR._

**Comment by haikyuu** [comment]
# Issue summary

`tree-sitter highlight` and `tree-sitter test` don't behave in the same way. 
- Test command works with the language defined in the current folder. 
- Highlight requires adding the parent-folder path to `"parser-directories"` in the config file (that's the solution)

# Preferred solution
- Make Highlight behave just like test. 

I hope this helps

**Comment by bartek** [comment]
I was having trouble with this too. Installed tree-sitter via homebrew on macOS. tree-sitter highlight could not find the language as others have stated.

Adding my workspace (`/Users/bartek/workspace`) which contains my tree-sitter grammar project (`/Users/bartek/workspace/tree-sitter-mine`) to tree-sitter parser-directories resolved the issue:

```
; ~/Library/Application\ Support/tree-sitter/config.json
"parser-directories": [
    "/Users/bartek/github",
    "/Users/bartek/src",
    "/Users/bartek/source",
    "/Users/bartek/workspace"
  ],  
```

Asking for a highlight of the file no longer complains

**Comment by ahlinc** [comment]
**TODO:**
- [ ] `tree-sitter highlight` - in case of a language wasn't find show an error with a list of configured paths and that there is no folder matched pattern `tree-siiter-<LANGNAME>` and no any other folder with specified `scope: "source.<LANGNAME>"` that is actually a tree-sitter language. If a folder matched pattern and is actually a language folder then use it but show a warning that the `tree-sitter.scope` should be explicitly specified.
- [ ] If a language was found and contains `query/highlights.scm` then use it by default but show a warning that all scm files should be explicitly specified in the `tree-sitter[].highlights[]` list of a `package.json` file.

**Comment by ethindp** [comment]
I'm running into this problem on Windows. Moved files around, got the naming properly for the directory, and tree-sitter still complains that no languages were found. (This is for tree-sitter parse, but I imagine it'll happen for anything else that needs the configuration system.) I followed the normal project setup steps, and then did `tree-sitter init-config`, and then `tree-sitter parse --stat --quiet <path to test files>`. And yes, the directory my project is in the list of configured parser locations.

**Comment by ahlinc** [comment]
@ethindp try to use a CLI version from my fork, it has some patches that were not upstreamed yet. 

`cargo install --git https://github.com/ahlinc/tree-sitter --branch alpha`

And could you show what `tree-sitter dump-languages` shows for you?

**Comment by ethindp** [comment]
@ahlinc It shows no output.

**Comment by ahlinc** [comment]
> @ahlinc It shows no output.

Try to clone some other official grammars in some of folders mentioned in TS config generated by `tree-sitter init-config` and dump langs again.

**Comment by ethindp** [comment]
@ahlinc I tried with the C grammar and it works. I just tried defining a tree-sitter config in package.json, and it still can't find it, but it can (apparently) find other repositories I clone.

**Comment by ahlinc** [comment]
@ethindp could you show your package.json? There in a tree-sitter section should be a scope and a file extensions fields.

Also in Tree-sitter's config should be mentioned a base folder that contains your  grammar folder. Also try to name your grammar folder with a `tree-sitter-` prefix before your lang name.

**Comment by ethindp** [comment]
@ahlinc I fixed it, my JSON file had a syntax error. (Oops?)

**Comment by ethindp** [comment]
Though actually building it doesn't work.... It looks like tree-sitter is just assuming that I'm using GCC or a gcc-compatible C compiler...

**Comment by ahlinc** [comment]
On windows it expects MS `cl.exe`

**Comment by ethindp** [comment]
I'm on Windows and it's invoking cl.exe as though it were GCC or clang:

```
    Command: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-shared" "-W4" "-fno-exceptions" "-o" "...\\AppData\\Local\\tree-sitter\\lib\\ada.dll" "...\\source\\tree-sitter-ada\\src\\parser.o"
 Stdout:    Creating library ...\AppData\Local\tree-sitter\lib\ada.lib and object ...\AppData\Local\tree-sitter\lib\ada.exp
    LINK : fatal error LNK1561: entry point must be defined
```

If I just start from the beginning it tries to compile a non-existent file (`%PWD%\src\parser.o`).

**Comment by ahlinc** [comment]
CL allows to use dashes on most of options.

**Comment by ethindp** [comment]
Yeah but I'm pretty sure none of it's options are `-fno-exceptions`, and it mentioned several deprecated options. I'm not sure how to get around the non-existent file problem though.

**Comment by ahlinc** [comment]
I'm not tested my fork on Windows, does the same compilation problem happens to upstream CLI?

**Comment by ethindp** [comment]
@ahlinc Nope, it works fine on the upstream CLI. Now I'm just getting `ERROR` AST nodes without any explanation or what was expected.

**Comment by ruuda** [comment]
I think there is still room for a more helpful error here. I found this issue after Googling for the error message. `tree-sitter dump-languages` would list my parser directory, but all of the fields (`scope`, `file_types`, etc.) would be empty. It turns out this was because I made `injection_regex` a list instead of a string.

After diving into the source code, one problem occurs here: https://github.com/tree-sitter/tree-sitter/blob/2d652c90a7c60efe4b2820e257a7e79c1c5017d9/cli/loader/src/lib.rs#L952-L953

If Serde fails to deserialize the `package.json` because it has the wrong schema, instead of failing loudly and reporting what is wrong with the `package.json` (Serde does include that in the error), the error gets silently ignored and instead we use default values: https://github.com/tree-sitter/tree-sitter/blob/2d652c90a7c60efe4b2820e257a7e79c1c5017d9/cli/loader/src/lib.rs#L1057-L1074

I see a few other people in this thread who ran into the problem due to syntax or schema errors in the `package.json`, it would be nice if `tree-sitter` would be able to report the problem instead of using a default value.

I quickly tried to replace the `if let Ok(...)` with just returning an `Err`, but that causes the parser directory to be ignored instead of reporting the error, so making this user-friendly will probably require more invasive changes. Maybe instead of returning `Result<&[LanguageConfiguration]>`, the function could return `Vec<Result<LanguageConfiguration>>`? For everything that looks like a parser and that can be loaded it returns `Ok`, for everything that looks like a parser but fails to load (for example due to `package.json` failing to deserialize) return an `Err`.

**Comment by Hofsiedge** [comment]
Had a similar issue, but in my case it was due to an incorrect directory name. I missed [this part](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#paths) of documentation:
> Currently, any folder within one of these parser directories **whose name begins with `tree-sitter-`** will be treated as a Tree-sitter grammar repository.

**Comment by chad-russell** [comment]
Had this same issue, after much trial and error I finally found that I had 

```json
"file-types": [".foo"]
```

instead of 
```json
"file-types": ["foo"]
```

 in my `tree-sitter.json` config file. The leading `.` is not allowed.

Even more confusing to me was that `tree-sitter parse file.foo` worked just fine, so there was really no reason to suspect it didn't like the file suffix.

This is the 4th or 5th head-scratch I've run into with no indication what went wrong. The error reporting in this project could use some *serious* work, otherwise it's pretty great. Anyway, hope this helps someone

**Comment by teohhanhui** [comment]
I was using `tree-sitter-cli` from Fedora repos, and `tree-sitter dump-languages` would just silently give everything `[]` or `None` for all the parser directories.

After removing the repo's `tree-sitter-cli` and reinstalling with:

```
cargo install --locked tree-sitter-cli
```
(https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md#installation)

It works properly.
