### ISSUE TITLE
Tree-sitter 1.0 Checklist

### ISSUE THREAD

**Issue by maxbrunsfeld** [tree-sitter/tree-sitter#930]
In the not-too-distant future, I'd like to bump Tree-sitter's version to 1.0, indicating a greater degree of stability and completeness. After that I'd like to regenerate all of the parsers in the `tree-sitter` org, and bump them to 1.0 as well. Before doing this, there are several important problems with the framework that I think should be fixed.

## Tasks

* [ ] **Unicode character properties** - Support ECMAScript unicode property escapes in regexes.
  * [x] Implement basic support for this construct (https://github.com/tree-sitter/tree-sitter/pull/906)
  * [ ] Regenerate all parsers to use unicode property escapes, fix any bugs that surface

* [ ] **Partial Precedence Orderings** - The integer precedence system makes some grammars shockingly difficult to maintain. Enhance the precedence system to allow precedences to be expressed in a pairwise *partial ordering* instead of requiring a total ordering based on integers.
  * [ ] Update `tree-sitter-javascript` and `tree-sitter-typescript` to use this more flexible precedence scheme. Right now, the integer precedence system is making it very difficult to continue development of `tree-sitter-typescript` in particular, because of the mix of different conflicts between types and expressions.
  * *Dynamic* precedence should probably stay integer-only, for simplicity

* [ ] **Mergeable Git Repos** - Make it easier to collaborate on grammars by removing generated files from version control.
  * [ ] **CLI commands** - Add new `pack` and `publish` subcommands to the Tree-sitter CLI, for uploading tarballs and compiled `.wasm` files to the GitHub releases API.
  * [ ] **Downstream** - Update GitHub's internal services to stop consuming Tree-sitter grammars using Git, and to start downloading them as tarballs from the GitHub releases API.
  * [ ] **Cleanup** - Remove generated files from all the grammar repos in the `tree-sitter` org

* [ ] **Grammars with many fields, aliases** - By historical accident, generated parsers use too small an integer type (`uint8_t`) for storing nodes' field and alias information. Parsers with large numbers of fields can cause integer overflows (https://github.com/tree-sitter/tree-sitter/issues/511)
  * [ ] Start representing nodes' `production_id` as a `uint16_t`
  * [ ] **Strategy** - Decide whether we're going to bother to maintain backward compatibility with old generated parsers, if so, the library code will need to become a bit more complicated in order to consume both binary formats.
  * [ ] **Grammars** - Regenerate all the parsers with the new representation.

* [ ] **CLI Ergonomics**
  * [ ] In `parse` command, auto-detect UTF-16 files and decode them accordingly. This will help windows users who currently trip over the suggested `echo` command in the docs.

* [ ] **Documentation**
  * [ ] Document the ability to match against supertypes in queries with the `expression/identifier` syntax.
  * [ ] Add more thorough explanations of LR conflicts, precedence, and dynamic conflict-resolution with GLR.
  * [ ] Make it clear how to use Tree-sitter for basic syntax highlighting *without* the `tree-sitter-highlight` rust crate (just using tree queries directly).
  * [ ] Create a CHANGELOG file and start maintaining it

## Stretch Goals

I'm recording these here even though they are a bit less urgent.

* [ ] **Incremental Parsing Perf** - Enhance the external scanner API to allow for looser state comparisons, avoiding the catastrophic node-reuse failures seen in the HTML parser (https://github.com/tree-sitter/tree-sitter-html/issues/23)
  * [ ] Figure out if the new scanner function can be made *optional* (with the parser generator inspecting `scanner.c` to decide whether to link against a `_compare` function).
  * [ ] Update `tree-sitter-html` to use this API, improving its incremental performance
  
* [ ] **Native Library, WASM parsers** - Add a compile-time option to link the C library against a [standard WASM engine](https://github.com/WebAssembly/wasm-c-api). When this feature is enabled, allow the native library to load WASM parsers, marshaling the parse table into native memory, and using WASM execution only for the *lexing* phase. This will make it more useful to distribute parsers as pre-compiled `.wasm` files, instead of as C code. The performance cost should be small, because all of the expensive operations will still be native.

**Comment by maxbrunsfeld** [comment]
For anyone who is interested, please let me know if I've left important things off of this list ☝️ .

**Comment by Razzeee** [comment]
Reads like tag queries are not going to be a 1.0 feature?

**Comment by theHamsta** [comment]
An alternative to removing the generated files would be to let them be pushed automatically on master by a CI bot. User can create mergable PRs by not needing to change any generated files. In this repo https://github.com/neovim/nvim-lspconfig/blob/master/.github/workflows/docgen.yml user coot changes to a configuration and a bit updates the documentation after each push on master.

**Comment by Razzeee** [comment]
I think https://github.com/tree-sitter/tree-sitter/issues/516 should also be addressed, even if the function is marked experimental? At least document the behavior.

**Comment by ahlinc** [comment]
I would suggest to reduce implicitness:
- [ ] Provide `dsl.js` as a regular file shipped with the `tree-sitter-cli` npm package and make it possible to require it as a regular JS library. This would help to extend it easily and would reduce confusion for IDEs and auto completion functionality in them. Behavior when `dsl.js` is embed in tree-sitter binary also would be good to save if the `dsl.js` wasn't required in the grammar file explicitly, this will allow to continue to use `tree-sitter` CLI as pretty standalone tool. Also this will make possible to separate the `grammar.json` generation in case of extended DSL or simplify its generation debugging as a regular node.js script.
- [ ] If to talk about tree-sitter's independence it would be good that tree-sitter would have [an embedded JS runtime #465](https://github.com/tree-sitter/tree-sitter/issues/465) with a fallback to a system `node.js` if this is requested explicitly by some CLI parameter, IMO a [deno library](https://github.com/denoland/deno) looks promising.

**Comment by ahlinc** [comment]
Also I saw that `*.so` files always have zeros in version spec like `libtree-sitter.so.0.0` it would be good that minimal ABI compatible version would be reflected in the `*.so.X.X` suffix somehow.

**Comment by dcreager** [comment]
Note that the version number in those file names aren’t the same as the 1.0 semver release that @maxbrunsfeld is proposing. If there are any backwards incompatible changes as part of putting together this release, we’d bump the SOVERSION to 1; if not, we’d keep it at 0. More details can be found [here](https://dcreager.net/shared-library-versions/).

**Comment by maxbrunsfeld** [comment]
@Razzeee Tag queries are already done, but you're right that we still need to document them. I envision those mostly being documented in a GitHub-specific context, since there isn't much generally-useful functionally specific to Tags; it's mostly just a convention that GitHub is using for code navigation. I added that to the TODOs around documentation though.

> I think #516 should also be addressed, even if the function is marked experimental?

Yeah, you're right about that API being broken. I'm inclined to just address that for 1.0 by marking the function as half-baked. For our use cases, the API was only ever needed for the Haskell parser, and then we discontinued development of that parser because it was hard to find a good subset of the language that was amenable to parsing with a context-free grammar. It could definitely be made to work some day, but I think it's low-priority for us.

**Comment by Razzeee** [comment]
> @Razzeee Tag queries are already done, but you're right that we still need to document them. I envision those mostly being documented in a GitHub-specific context, since there isn't much generally-useful functionally specific to Tags; it's mostly just a convention for tree queries that GitHub is using for code navigation. All of the broadly-useful stuff has been generalized into the query system. I added that to the TODOs around documentation though.

So you don't think tags make sense for others? I hoped, that it would help moving the queries towards the parser and thus having multiple projects consume these/improve these.

> 
> > I think #516 should also be addressed, even if the function is marked experimental?
> 
> Yeah, you're right about that API being broken. I'm inclined to just address that for 1.0 by marking the function as half-baked. For our use cases, the API was only ever needed for the Haskell parser, and then we discontinued development of that parser because it was hard to find a good subset of the language that was amenable to parsing with a context-free grammar. It could definitely be made to work some day, but I think it's low-priority for us. There is still a bit of work to do to get it to play properly with incremental parsing.

Understandable, do I need to be worried about the incremental parsing bit? Moved our parser to use this on a regular basis now and it seemed good, after figuring out, while it always gets stuck...

**Comment by Razzeee** [comment]
Nice strech goals would be:
- https://github.com/tree-sitter/tree-sitter/pull/729 
- https://github.com/tree-sitter/tree-sitter/issues/255

**Comment by ubolonton** [comment]
> **CLI commands** - Add new `pack` and `publish` subcommands to the Tree-sitter CLI, for uploading tarballs and compiled `.wasm` files to the GitHub releases API.

This is awesome. Currently for Emacs, I have a custom [package](https://github.com/ubolonton/tree-sitter-langs/) that compiles the grammar binaries for the 3 major platforms, and distributes them through GitHub Releases, in a single bundle. Having a standard tool for individual language package to do this on their own would be great.

Will the official language repositories start distributing these binaries through GitHub Releases as well? I think some GitHub actions on top of these subcommands would be very helpful for that.

**Comment by maxbrunsfeld** [comment]
@ubolonton I might not take on the automation of compilation and storage of binary files (except for wasm) right now. I was mostly planning to use GH releases to store tarballs of generated files like `parser.c`, to avoid having so many merge conflicts in development.

**Comment by WhyNotHugo** [comment]
> Add new pack and publish subcommands to the Tree-sitter CLI, for uploading tarballs and compiled .wasm files to the GitHub releases API.

I find this item problematic; what about tree-sitter implementations that are not hosted on GitHub? What's the plan on how those should be redistributed?

**Comment by dcreager** [comment]
@WhyNotHugo Yes, to confirm, the plan is **_not_** to mandate any particular hosting platform. Those commands will be able to produce the generated artifacts without uploading them as a GitHub release.

**Comment by maxbrunsfeld** [comment]
@Razzeee I think you're right that the `get_column` problem is important. It's especially relevant now that `tree-sitter-haskell` has been revived from the dead (thanks @tek). I believe I've addressed all of the problems with that API.

**Comment by Razzeee** [comment]
while I agree, feel it's disappointing that it needed that to happen. as there have been other grammars suffering from it. still, thank you <3

**Comment by ahlinc** [comment]
It would be awesome to automate release process for all official tree-sitter tools, especially for [tree-sitter-cli](https://github.com/tree-sitter/tree-sitter/tree/master/cli/npm), for all official bindings [Wasm](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web), [Rust](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_rust), [Node.js](https://github.com/tree-sitter/node-tree-sitter), [Python](https://github.com/tree-sitter/py-tree-sitter), [Haskell](https://github.com/tree-sitter/haskell-tree-sitter), [Ruby](https://github.com/tree-sitter/ruby-tree-sitter) and [the Playground](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-7-playground.html) with its [separately living parsers](https://github.com/tree-sitter/tree-sitter.github.io) and keep all in sync with the core [tree-sitter](https://github.com/tree-sitter/tree-sitter/tree/master/lib/src) library releases. This would help to reduce misunderstanding and situations that some things work somewhere and somewhere don't.

**Comment by XVilka** [comment]
I am not sure if this is actually possible - it would be also awesome if generated parser/runtime never segfaults. Showing errors, warnings, exiting - yes, but never segfaulting.

**Comment by maxbrunsfeld** [comment]
> I am not sure if this is actually possible - it would be also awesome if generated parser/runtime never segfaults.

Obviously the library should never segfault. AFAIK, that's already the case. I think you're referencing https://github.com/tree-sitter/tree-sitter-c/issues/64, which I can't reproduce after stripping out third-party libraries.

If anyone is seeing Tree-sitter cause a segfaults, and you can reproduce the problem, please report it.

**Comment by Julian** [comment]
I've definitely seen segfaults from my (nonideal) grammar recently. I'll try and collect a backtrace.

**Comment by casouri** [comment]
tree-sitter should provide means to replace memory allocation functions at _runtime_. This allows us to link to tree-sitter as a library instead of embedding it.

**Comment by SNDST00M** [comment]
Can all `tree-sitter-*` packages be updated? Currently the extension is using 0.16 which is broken:

* #28
* https://github.com/tree-sitter/tree-sitter/issues/571
* https://github.com/tree-sitter/tree-sitter/pull/822

**Comment by stevenbarragan** [comment]
+1 for [better error messages](https://github.com/tree-sitter/tree-sitter/issues/255).
[related comment](https://github.com/tree-sitter/tree-sitter/pull/946#issuecomment-786901045)

**Comment by CreatCodeBuild** [comment]
__Native Library, WASM parsers__ I would love to use wasm in other runtimes. Currently I am only able to use wasm in JS. But I would want to use it in wasmer and I don't want to use the c version because the same parser is run in different runtimes.

**Comment by oovm** [comment]
For **wasm target**, how about [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen), which can generate Rust 
 and Typescript binding at the same time.

Typescript typing is really useful when working with VSCode LSP(Language Server Protocol)

**Comment by matu3ba** [comment]
When do you plan to document parsing and query performance or some of the internal data structure to estimate those in complexity classes, so O(1|log n|n|..)?

I also do see [the implementation docs look relative incomplete](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-5-implementation.md#the-runtime). so probably they also belong on the TODO list?

Background is that I wanted to check the datastructure + complexity of a query on editing. I was checking `query.c` and found https://github.com/tree-sitter/tree-sitter/blob/1fe0420f0fe3df633c4f8b80d0c991a7aa214eeb/lib/src/query.c#L672
```txt
// The entries are sorted by the patterns' root symbols, and lookups use a
// binary search. This ensures that the cost of this initial lookup step
// scales logarithmically with the number of patterns in the query.
```
which sounds good to mention in the docs. However this only mentions "initial lookup step" and not overall worst case performance per pattern match or is unlucky formulated.

Reason was that I wanted to check out of curiosity, how performance compares to [this approach](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization).

**Comment by JuneKelly** [comment]
Forgive me if this is addressed elsewhere, but as a newcomer to tree-sitter, I'd love to be able to implement external scanners in a language like Rust, Nim, Zig, or something along those lines, rather than C/C++.

(Wonderful project by the way, thanks for everything!)

**Comment by archseer** [comment]
It should be possible if you export the same C ABI. I'd advise against it if possible though, because it imposes additional build dependencies when compiling the grammar.

**Comment by wkordalski** [comment]
> Native Library, WASM parsers - Add a compile-time option to link the C library against a [standard WASM engine](https://github.com/WebAssembly/wasm-c-api) (V8, wasmtime, or wasmer). When this feature is enabled, allow the native library to load WASM parsers, marshaling the parse table into native memory, and using WASM execution only for the lexing phase. This will make it more useful to distribute parsers as pre-compiled .wasm files, instead of as C code. The performance cost should be small, because all of the expensive parsing operations will still be native.

I  write Rust application that is compiled to `wasm32-unknown-unknown` and uses Tree-sitter for parsing.
Right now I use Rust bindings to `web-tree-sitter` (which is: Javascript bindings to Tree-sitter compiled to `wasm32-unknown-emscripten`). It would be really nice if I could compile Tree-sitter library and parsers to `wasm32-unknown-unknown` link with other Rust-to-WASM compiled stuff, and this way get rid of JavaScript-as-a-proxy between my WASM and Tree-sitter WASM.

**Comment by lambdadog** [comment]
> * [ ]  **Native Library, WASM parsers** - Add a compile-time option to link the C library against a [standard WASM engine](https://github.com/WebAssembly/wasm-c-api) (V8, wasmtime, or wasmer). When this feature is enabled, allow the native library to load WASM parsers, marshaling the parse table into native memory, and using WASM execution only for the _lexing_ phase. This will make it more useful to distribute parsers as pre-compiled `.wasm` files, instead of as C code. The performance cost should be small, because all of the expensive parsing operations will still be native.

To clarify, do you want this to be WASM engine implementation agnostic, as per your link to `wasm-c-api`, or is it fine to just embed a specific WASM engine?

There's no reason I can think of to stay agnostic, though I'd be happy to be corrected, and I imagine it would be simpler to just use wasmtime or wasmer's native Rust APIs rather than having to go through the C ABI.

**Comment by aMOPel** [comment]
This might go against the inner design or the philosophy, but from the standpoint of a parser author for a whitespace sensitive language, it would be great to have some first class support for whitespace matching (identation, dedentation, newlines) when writing a parser.

**Comment by drwpow** [comment]
**Suggestion: ESM format**

In the interest of an evergreen format I’d like to recommend [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) over CJS (e.g. basically just changing `module.exports` to `export default`. Now that that’s the official module system of JS in all forms and is supported on web and Node.js, that’s a breaking change that would be easier to do sooner than later.

Happy to help with this if this is a desirable change! But just a suggestion I’ll leave to the author/maintainers to decide 🙂

**Comment by maxbrunsfeld** [comment]
> Suggestion: ESM format

Yeah, I've been thinking about this too @drwpow. I added this to the list, as well as an item about reducing our coupling to npm in general.

> To clarify, do you want this to be WASM engine implementation agnostic, as per your link to wasm-c-api, or is it fine to just embed a specific WASM engine?

@lambdadog I started work on this issue in #1864. I ended up going with a solution that's specifically tied to wasmtime for now.

**Comment by kevinbarabash** [comment]
@maxbrunsfeld I worked around the issue of having to check-in build files by running `yarn install` and `yarn generate` as part of the build.rs file.  Thankfully `yarn generate` doesn't clobber this file.  One issue I ran into is that binding.gyp cannot be checked in otherwise `yarn install` fails.  I got around this by renaming it to real-binding.gyp and then copying it to binding.gyp after running `yarn install`.  This seems to work even if it is a bit janky.  See https://github.com/crochet-lang/crochet/pull/288 to see this approach in action.

**Comment by Kennobi19** [comment]
> In the not-too-distant future, I'd like to bump Tree-sitter's version to 1.0, indicating a greater degree of stability and completeness. After that I'd like to regenerate all of the parsers in the [tree-sitter](https://github.com/tree-sitter) github org, and bump them to 1.0 as well. Before doing this, there are several important problems with the framework that I think should be fixed.
> 
> ## Tasks
> * [x]  **Unicode character properties** - Support ECMAScript unicode property escapes in regexes.
>   
>   * [x]  Implement basic support for this construct ([Handle simple unicode property escapes in regexes #906](https://github.com/tree-sitter/tree-sitter/pull/906))
>   * [x]  Regenerate all parsers to use unicode property escapes, fix any bugs that surface
> * [x]  **Partial Precedence Orderings** - The integer precedence system makes some grammars shockingly difficult to maintain.
>   
>   * [x]  Enhance the precedence system to allow precedences to be expressed in a pairwise _partial ordering_ instead of requiring a total ordering based on integers. ([Allow precedences to be specified using strings and a partial ordering relation #939](https://github.com/tree-sitter/tree-sitter/pull/939))
>   * [x]  Update `tree-sitter-javascript` and `tree-sitter-typescript` to use this more flexible precedence scheme. Right now, the integer precedence system is making it very difficult to continue development of `tree-sitter-typescript` in particular, because of the mix of different conflicts between types and expressions.
>   * _Dynamic_ precedence should probably stay integer-only, for simplicity
> * [x]  **Grammars with many fields, aliases** - By historical accident, generated parsers use too small an integer type (`uint8_t`) for storing nodes' field and alias information. Parsers with large numbers of fields can cause integer overflows ([Tree-sitter generates invalid code for grammars with large numbers of fields and/or aliases #511](https://github.com/tree-sitter/tree-sitter/issues/511))
>   
>   * [x]  Start representing nodes' `production_id` as a `uint16_t` ([Clean up parse table representation, use 16 bits for production_id #943](https://github.com/tree-sitter/tree-sitter/pull/943))
>   * [x]  **Strategy** - Decide whether we're going to bother to maintain backward compatibility with old generated parsers, if so, the library code will need to become a bit more complicated in order to consume both binary formats.
>   * [x]  **Grammars** - Regenerate all the parsers with the new representation.
> * [x]  Fix issues with the `get_column` external scanner API ([Fix the behavior of Lexer.get_column #978](https://github.com/tree-sitter/tree-sitter/pull/978))
> * [ ]  **CLI Ergonomics**
>   
>   * [x]  Generate Rust bindings for parsers, and structure the Node.js bindings more consistently with the Rust ones ([In the generate command, create rust binding files #948](https://github.com/tree-sitter/tree-sitter/pull/948))
>   * [ ]  In `parse` command, auto-detect UTF-16 files and decode them accordingly. This will help windows users who currently trip over the suggested `echo` command in the docs.
>   * [ ]  Support grammars defined as [ECMAScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) instead of CommonJS module.
>   * [ ]  **Reduce Coupling to Node** - Introduce some Tree-sitter specific `GRAMMAR_PATH` setting where the CLI will search for grammar modules, instead of relying on `node_modules` and `npm`.
> * [ ]  **Mergeable Git Repos** - Make it easier to collaborate on grammars by removing generated files from version control.
>   
>   * [ ]  **CLI commands** - Add new `pack` and `publish` subcommands to the Tree-sitter CLI, for uploading tarballs and compiled `.wasm` files to the GitHub releases API. [Store generated files as GH release artifacts instead of checking them into git repositories #730 (comment)](https://github.com/tree-sitter/tree-sitter/issues/730#issuecomment-736018228)
>   * [ ]  **Downstream** - Update GitHub's internal services to stop consuming Tree-sitter grammars using Git, and to start downloading them as tarballs from the GitHub releases API.
>   * [ ]  **Cleanup** - Remove generated files from all the grammar repos in the tree-sitter org
> * [ ]  **Documentation**
>   
>   * [ ]  Document the ability to match against supertypes in queries with the `expression/identifier` syntax.
>   * [ ]  Add more thorough explanations of LR conflicts, precedence, and dynamic conflict-resolution with GLR.
>   * [ ]  Make it clear how to use Tree-sitter for basic syntax highlighting _without_ the `tree-sitter-highlight` rust crate (just using tree queries directly).
>   * [x]  Document the `tags.scm` queries used for code navigation on GitHub. [Document `queries/tags.scm` #660](https://github.com/tree-sitter/tree-sitter/issues/660)
>   * [ ]  Create a CHANGELOG file and start maintaining it. [Wish: CHANGELOG #527](https://github.com/tree-sitter/tree-sitter/issues/527)
> 
> ## Stretch Goals
> I'm recording these here even though they are a bit less urgent.
> 
> * [ ]  **Incremental Parsing Perf** - Enhance the external scanner API to allow for looser state comparisons, avoiding the catastrophic node-reuse failures seen in the HTML parser ([Incremental parsing is ineffective when a new tag is opened tree-sitter-html#23](https://github.com/tree-sitter/tree-sitter-html/issues/23))
>   
>   * [ ]  Figure out if the new scanner function can be made _optional_ (with the parser generator inspecting `scanner.c` to decide whether to link against a `_compare` function).
>   * [ ]  Update `tree-sitter-html` to use this API, improving its incremental performance
> * [ ]  **Native Library, WASM parsers** - Add a compile-time option to link the C library against a [standard WASM engine](https://github.com/WebAssembly/wasm-c-api) (V8, wasmtime, or wasmer). When this feature is enabled, allow the native library to load WASM parsers, marshaling the parse table into native memory, and using WASM execution only for the _lexing_ phase. This will make it more useful to distribute parsers as pre-compiled `.wasm` files, instead of as C code. The performance cost should be small, because all of the expensive parsing operations will still be native. [Add optional WASM feature to the native library, allowing it to run wasm-compiled parsers via wasmtime #1864](https://github.com/tree-sitter/tree-sitter/pull/1864)

**Comment by llllvvuu** [comment]
> distribute parsers as pre-compiled .wasm files, instead of as C code.

This may be naive (I'm very unfamiliar with parser tech), but I wonder if distributing parse tables is the fundamentally even the right thing. WASM or not (and WASM is better for distribution), they are still going to be much larger than the actual grammar/scanner definitions.

If there were a portable way to build these client-side (maybe not at runtime lol, but at install time?) then could that reduce download by a lot? So like the distribution format would be something `languagename-langversion-abiversion.tar.gz`.

The only problem is that the grammar is defined in JavaScript. I assume this is fossilized now. I saw some discussion here: https://github.com/tree-sitter/tree-sitter/issues/465. Maybe for Neovim/Helix/etc having a dependency on Node/QuickJS/etc would still be better than downloading 10+ MB .so/.wasm/etc files?

(even more wacky idea could be WASMception where you build the WASM in WASM)

**Comment by llllvvuu** [comment]
Another spitball idea could be to build some rudimentary package management into the tree-sitter lib itself, so that editors could call it for installation/resolution and never load an incompatible parser. It would not need to include any blessed package registry yet (editors can continue to map name -> URL themselves) but could handle the unpacking, (with optional extension) building, and loading - with a common install prefix (`$TREE_SITTER_PATH/$MAJOR_VERSION`)

**Comment by xiaoma20082008** [comment]
maybe this issue [Standardized node name](https://github.com/tree-sitter/tree-sitter/issues/195)  need to be released

**Comment by 0842359771** [comment]
>
